### ISSUE TITLE
Dataframe.append has been removed for pandas 2.0

### ISSUE THREAD

**Issue by kkumar5991** [addypy/datagovindia#5]
Dataframe.append has been removed for pandas 2.0 and gives an error. Previous versions also give warnings:

FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead. self.data = self.data.append(df, ignore_index=True)

Can this be updated?

**Comment by addypy** [comment]
@kishlaykumar1995 For now, I would recommend downgrading pandas if this is critical to you. We're working on the next version of datagovindia with major changes. However the next version is still a few weeks away since I am the sole maintainer.

**Comment by addypy** [comment]
@kishlaykumar1995 
This has been resolved in v1.0.0.
