### ISSUE TITLE
Read Timeout on sync

### ISSUE THREAD

**Issue by 4nuragk** [addypy/datagovindia#6]
![datagovin](https://github.com/addypy/datagovindia/assets/29572449/1cdfe7c5-4eb2-443a-89b7-6373329997ea)

This is happening both on cli and python

**Comment by addypy** [comment]
<img width="875" alt="datagovindia_cli" src="https://github.com/addypy/datagovindia/assets/54233083/8d9fa0cf-ed26-4b4f-b11b-cc1f25dadb25">

You can view ^ this using `datagovindia sync-metadata --help`

The `sync-metadata` tool has a `batch-size` option that you can experiment with to mitigate timeout errors. A larger batch size may run quicker but could lead to timeout errors if the server response is delayed. 

Please try starting with a high batch size, such as 1000:

```bash
datagovindia sync-metadata --batch-size=1000
```

If you encounter the same error, reduce the batch size incrementally until the command executes successfully. For example, you can try:

```bash
datagovindia sync-metadata --batch-size=500
```

or

```bash
datagovindia sync-metadata --batch-size=100
```

Let me know if adjusting the batch size resolves the issue, or if the issue persists.

**Comment by 4nuragk** [comment]
Specifying batch size 1000 solved the issue.
