### ISSUE TITLE
Issue with fetching data through the API

### ISSUE THREAD

**Issue by sdipti** [addypy/datagovindia#7]
I am trying the following code and it shows up an error.
```
pip install datagovindia
from datagovindia import DataGovIndia

import os
os.environ["DATAGOVINDIA_API_KEY"] = "MY_API_KEY"

data_gov = DataGovIndia()
data_gov.sync_metadata()
```
ERROR:

ConnectTimeout: HTTPSConnectionPool(host='api.data.gov.in', port=443): Max retries exceeded with url: /lists?format=json&notfilters%5Bsource%5D=visualize.data.gov.in&filters%5Bactive%5D=1&offset=0&limit=0 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7a1f96e30070>, 'Connection to api.data.gov.in timed out. (connect timeout=5)'))

Even when I try fetching the data using the following code, the same error shows up:

```
resource_id = "1d4d1c5a-feea-423b-be4f-c3636fdd1d82"
api_endpoint = f"https://api.data.gov.in/resource/{resource_id}?api-key={os.environ['DATAGOVINDIA_API_KEY']}&format=json&offset=0&limit=0&filters%5BcurrentStateName.keyword%5D=DELHI&filters%5Bgender.keyword%5D=FEMALE&filters%5Bage%5D=16"
import requests
response = requests.get(api_endpoint)
```

ERROR:
ConnectTimeout: HTTPSConnectionPool(host='api.data.gov.in', port=443): Max retries exceeded with url: /resource/1d4d1c5a-feea-423b-be4f-c3636fdd1d82?api-key=579b464db66ec23bdd000001ee3ad19e23d947ea77c4ec9d5c1a9de1&format=json&offset=0&limit=0&filters%5BcurrentStateName.keyword%5D=DELHI&filters%5Bgender.keyword%5D=FEMALE&filters%5Bage%5D=16 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7a1f96e318d0>, 'Connection to api.data.gov.in timed out. (connect timeout=None)'))

I am not sure whats going wrong, please help

**Comment by addypy** [comment]
Hi @sdipti 

Thank you for reporting this issue. After testing the same API calls on my end, it appears this might be a network-related issue. Please consider the following steps:

1. **Check Network Stability**: Ensure your internet connection and network settings (like firewalls or proxies).
2. **Retry Later**: The data.gov.in servers may sometimes experience downtime. Try accessing the API again after some time.
3. **Alternative Network**: If feasible, test the API from a different network.

If the problem persists, please let me know, including any error messages or changes you notice.

**Comment by sdipti** [comment]
Internet connection seems alright as of now, how can I check if the issue is due to firewall/proxies? And how can I fix them?

I shall try again tomorrow through a different network too. Is it possible that this may be happening as the data.gov.in servers are down? Are the codes running successfully at your end right now, because I tried these codes just now.

**Comment by addypy** [comment]
Yes it seems to be working correctly on my end. Are you able to access the data.gov.in website through your browser?

**Comment by sdipti** [comment]
Yes, I can access it on the browser

**Comment by addypy** [comment]
Are you using jupyter notebooks or a specific IDE? Which OS are you using? It's possible that network access to python is disabled in your system.

**Comment by sdipti** [comment]
I am using Python on Google Colab

**Comment by addypy** [comment]
It's possible that Colab is limiting your internet because `sync_metadata` downloads a lot of information about resources to a local SQLite database.

Here's what you should try:
- Restart your colab session: Go to `Runtime` > `Restart Session`
- If you already know the resource-id for the document you need, skip the `sync_metadata` step

```python
import os
from datagovindia import DataGovIndia
# Set your API key
os.environ['DATAGOVINDIA_API_KEY'] = "YOUR_API_KEY"
# Initialize DataGovIndia 
data_gov = DataGovIndia()
# Specify resource_id
resource_id = "1d4d1c5a-feea-423b-be4f-c3636fdd1d82"
## Get resource info
data_gov.get_resource_info(resource_id)
# Get data
data_gov.get_data(resource_id)
```

`sync_metadata` is useful if you need to use the `datagovindia` package for searching for resources. But even without it, if you already know the resource-ids you need, you can use the package to fetch them directly.

**Comment by sdipti** [comment]
I tried using the resource id too in my second set of code, but it still
throws a similar error. I tried it for a very small sample in the dataset,
so it doesn't look like a size/limit issue. What else could be the reason?

**Comment by addypy** [comment]
I think most likely Colab has restricted your network access. If you restart the session it should reset.

**Comment by sdipti** [comment]
I tried the above code as is and it throws the following error:

ConnectTimeout: HTTPSConnectionPool(host='api.data.gov.in', port=443): Max retries exceeded with url: /resource/1d4d1c5a-feea-423b-be4f-c3636fdd1d82?api-key=579b464db66ec23bdd000001ded4b40e8129445773969d708c7d21c9&format=json&offset=0&limit=0 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7a1f96e32530>, 'Connection to api.data.gov.in timed out. (connect timeout=5)'))

**Comment by addypy** [comment]
Did you restart your session? If so then I would suggest testing this on another platform, perhaps on your local system?

**Comment by sdipti** [comment]
Yes, I restarted the session. My local system has organisation restrictions unfortunately

**Comment by sdipti** [comment]
Ok, so I change the 'Runtime type' to T4 GPU and it seems to work partially. Now it throws a different error: 

HTTPError: 504 Server Error: Gateway Timeout for url: https://api.data.gov.in/resource/1d4d1c5a-feea-423b-be4f-c3636fdd1d82?api-key=579b464db66ec23bdd000001ded4b40e8129445773969d708c7d21c9&format=json&offset=36646000&limit=2000

What would this exactly mean?
